version: "3.9"
services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1.21-bullseye
    container_name: app
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "8080:8080"
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge