name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    env:
      COVERPROFILE: ./profile.cov
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x, 1.22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Run coverage only on Ubuntu with Go 1.22.x
        include:
          - os: ubuntu-latest
            go-version: 1.22.x
            coverage: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Run coverage
        if: ${{ matrix.coverage }}
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ${{ env.COVERPROFILE }}

  license-scan:
    name: License Scan
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Install FOSSA
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
  
      - name: Run FOSSA analysis
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: fossa analyze

      - name: Check FOSSA status
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: fossa test

  release:
    name: Release
    if: github.event_name == 'push'
    needs: [license-scan]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Run release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
