name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x, 1.22.x]
    name: Build
    runs-on: ubuntu-latest
    env:
      MONGO_SERVER_URL: mongodb://localhost:27017
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - mongodb:/data/db
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test and Coverage
        run: go test -v -coverprofile=./profile.cov ./...

      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ./profile.cov

  license-scan:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Install FOSSA
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
  
      - name: Run FOSSA analysis
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: fossa analyze

      - name: Check FOSSA status
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: fossa test

  semantic-release:
    needs: [license-scan]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Run semantic-release
        if: github.repository == 'bartventer/casbin-go-cloud-adapter' && github.event_name == 'push'
        run: |
          yarn global add semantic-release@17
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
